---
abstract: 'Interface to the Google Fusion Tables API'
author:
  - 'Robin Clarke <perl@robinclarke.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Fusion
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Encode: 0
  File::HomeDir: 0
  IO::String: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  Net::OAuth2::Moosey::Client: 0.02
  Test::More: 0
  Text::CSV: 0
  Text::Table: 0
  URL::Encode: 0
  YAML: 0
version: 0.08
