--- #YAML:1.0
name:               Google-Fusion
version:            0.04
abstract:           Interface to the Google Fusion Tables API
author:
    - Robin Clarke <perl@robinclarke.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Encode:               0
    File::HomeDir:        0
    LWP::Protocol::https:  0
    LWP::UserAgent:       0
    Moose:                0
    Net::OAuth2::Client:  0.1
    Test::More:           0
    Text::CSV:            0
    Text::Table:          0
    URL::Encode:          0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
